In [124]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [125]:
df = pd.read_csv('train.txt',sep = ';',header = None,names = ['text','emotion'])

In [126]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [127]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [128]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [129]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}

i = 0
for emo in unique_emotions:
    emotion_numbers[emo] = i;
    i += 1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [130]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

### Text Cleaning

In [131]:
# lowercasing
df['text'] = df['text'].apply(lambda x : x.lower())

In [132]:
# remove punctuation
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [133]:
df['text'] = df['text'].apply(remove_punc)

In [134]:
# remove numbers

def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new += i
    return new

In [135]:
df['text'] = df['text'].apply(remove_numbers)

In [136]:
# remove emojis & special character

def remove_emoji(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

In [137]:
df['text'] = df['text'].apply(remove_emoji)

In [138]:
# removing stopwords

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [139]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jangi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jangi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\jangi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\jangi\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\jangi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [140]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [141]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [142]:
def remove(txt):
    words = word_tokenize(txt)
    cleaned = []
    for i in words:
        if not i in stop_words:
            cleaned.append(i)
    return ' '.join(cleaned)

In [143]:
df['text'] = df['text'].apply(remove)

In [144]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [145]:
from sklearn.model_selection import train_test_split

In [146]:
x_train, x_test, y_train, y_test = train_test_split(
    df['text'], df['emotion'],
    test_size = 0.20, random_state = 42
)

In [147]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [148]:
bow_vectorizer = CountVectorizer()

In [155]:
x_train_bow = bow_vectorizer.fit_transform(x_train)
x_test_bow = bow_vectorizer.transform(x_test)

In [156]:
x_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116049 stored elements and shape (12800, 13359)>

In [157]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [158]:
nb_model = MultinomialNB()

In [159]:
nb_model.fit(x_train_bow,y_train)

MultinomialNB()

In [162]:
pred_bow = nb_model.predict(x_test_bow)

In [163]:
print(accuracy_score(y_test,pred_bow))

0.7678125

### Tf-idf

In [164]:
tfidf_vectorizer = TfidfVectorizer()

In [165]:
x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf = tfidf_vectorizer.transform(x_test)

In [166]:
x_train_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 116049 stored elements and shape (12800, 13359)>

In [167]:
nb2_model = MultinomialNB()

In [168]:
nb2_model.fit(x_train_tfidf,y_train)

MultinomialNB()

In [169]:
pred_tfidf = nb2_model.predict(x_test_tfidf)

In [170]:
print(accuracy_score(y_test,pred_tfidf))

0.6609375

#### tf-idf with logistic regression

In [171]:
from sklearn.linear_model import LogisticRegression

In [172]:
logistic_model = LogisticRegression(max_iter = 1000)

In [173]:
logistic_model.fit(x_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [174]:
log_pred_tfidf = logistic_model.predict(x_test_tfidf)

In [175]:
print(accuracy_score(y_test,log_pred_tfidf))

0.8615625